security:
   authorization: enabled
   keyFile: /appz/keys/key.txt
systemLog:
   destination: file
   path: "/appz/log/mongodb.log"
   logAppend: true
#storage:
 #  journal:
  #    enabled: true
net:
   bindIpAll: true
replication:
   oplogSizeMB: 10000
   replSetName: rs0
