[program:custom_metrics]
command                 = bash -c "/appz/scripts/custom_metrics.sh"
autostart               = true
autorestart             = true
stdout_logfile          = /appz/log/custom_metrics.log
stderr_logfile          = /appz/log/custom_metrics_error.log

