[program:minio_backup]
command                 = bash -c "/appz/scripts/minio_backup.sh"
autostart               = false
autorestart             = false
stdout_logfile  = /appz/log/%(program_name)s.log
stderr_logfile  = /appz/log/%(program_name)s.log
redirect_stderr = true
