apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-home
  namespace: myco-dev
spec:
  storageClassName: vault-home
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: myco-dev
spec:
  storageClassName: vault-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
