[program:addusers]
command                 = /appz/scripts/addusers.sh
autostart               = true
autorestart             = false
user = root
startretries = 1
stdout_logfile  = /appz/log/%(program_name)s-stdout.log
stderr_logfile  = /appz/log/%(program_name)s-stderr.log
