[program:mongo_backup]
command                 = /appz/scripts/mongo_backup.sh
autostart               = false
autorestart             = false
stdout_logfile  = /appz/log/%(program_name)s.log
stderr_logfile  = /appz/log/%(program_name)s.log
