[program:exporter]
command                 = bash /appz/scripts/mongoexporter.sh
autostart               = true
autorestart             = true
startretries            = 10
user = root
stdout_logfile  = /appz/log/%(program_name)s-stdout.log
stderr_logfile  = /appz/log/%(program_name)s-stderr.log
