[program:mongo]
command         = bash /appz/scripts/start.sh
autostart               = true
autorestart             = true
startretries            = 10
stdout_logfile  = /appz/log/%(program_name)s.log
stderr_logfile  = /appz/log/%(program_name)s.log
exitcodes=0
stopsignal=TERM
stopwaitsecs=30
stopasgroup=true
killasgroup=true

