[program:grafana]
command                 = /appz/scripts/run.sh 
startretries            = 0
autostart		= true
autorestart		= true
redirect_stderr         = true
stdout_logfile	        = /appz/log/%(program_name)s.log
