{
 "title": "AppZ Redis - v2",
 "description": "Redis Dashboard",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": {
     "query": "label_values(origin prometheus)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(redis_uptime_in_seconds{origin_prometheus=~\"$origin_prometheus\"},job)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(redis_up{namespace=~\"$namespace\", origin_prometheus=~\"$origin_prometheus\", job=\"$job\"},instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(redis_up, namespace)"
   },
   {
    "name": "pod",
    "label": "Pods",
    "query": "label_values(redis_up{instance=~\"$host\", namespace=\"$namespace\"}, pod)"
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Max Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Total Commands / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"} [1m])) by (cmd)",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "hits, {{ pod }}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "misses, {{ pod }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "used, {{ pod }}"
    },
    {
     "expr": "redis_memory_max_bytes{instance=~\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "max, {{ pod }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(rate(redis_net_output_bytes_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (db, pod)",
     "legendFormat": "{{ db }}, {{ pod }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (pod) - sum (redis_db_keys_expiring{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "not expiring, {{ pod }}"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "expiring, {{ pod }}"
    }
   ]
  },
  {
   "title": "Expired/Evicted Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "expired, {{ pod}}"
    },
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "evicted, {{pod }}"
    }
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "connected"
    },
    {
     "expr": "sum(redis_blocked_clients{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "blocked"
    }
   ]
  },
  {
   "title": "Average Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (cmd)\n  /\nsum(irate(redis_commands_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[1m])) by (cmd) != 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}