{
 "title": "AppZ OpenSearch - v1",
 "description": "OpenSearch cluster stats.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(opensearch_node_role_bool,instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(opensearch_cluster_nodes_number,cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node name",
    "query": {
     "query": "label_values(opensearch_node_role_bool{cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "opensearch_cluster_status" }
   ]
  },
  {
   "title": "Tripped for breakers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "opensearch_circuitbreaker_tripped_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_process_cpu_percent{instance=~\"$instance\",cluster=\"$cluster\",node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "JVM Heap memory used Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_jvm_mem_heap_used_percent{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_cluster_nodes_number{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_cluster_datanodes_number{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Pending tasks",
   "type": "stat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_cluster_pending_tasks_number{instance=\"$instance\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors per cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (opensearch_process_file_descriptors_open_number{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active primary shards",
   "type": "stat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_cluster_shards_number{instance=\"$instance\",cluster=\"$cluster\",type=\"active_primary\"}"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "stat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_cluster_shards_number{instance=\"$instance\",cluster=\"$cluster\",type=\"active\"}"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "stat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_cluster_shards_number{instance=\"$instance\",cluster=\"$cluster\",type=\"initializing\"}"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "stat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_cluster_shards_number{instance=\"$instance\",cluster=\"$cluster\",type=\"relocating\"}"
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "stat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_cluster_shards_number{instance=\"$instance\",cluster=\"$cluster\",type=\"unassigned\"}"
    }
   ]
  },
  {
   "title": "JVM Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(opensearch_jvm_gc_collection_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}} - {{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(opensearch_jvm_gc_collection_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}} - {{gc}}"
    }
   ]
  },
  {
   "title": "Translog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total translog operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(opensearch_index_translog_operations_number{instance=\"$instance\",cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total translog size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(opensearch_index_translog_size_bytes{instance=\"$instance\",cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "Total size"
    }
   ]
  },
  {
   "title": "Breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tripped for breakers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "opensearch_circuitbreaker_tripped_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
     "legendFormat": "{{node}}: {{breaker}}"
    }
   ]
  },
  {
   "title": "Estimated size in bytes of breaker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "opensearch_circuitbreaker_estimated_bytes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
     "legendFormat": "{{node}}: {{breaker}}"
    },
    {
     "expr": "opensearch_circuitbreaker_limit_bytes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
     "legendFormat": "{{node}}: limit for {{breaker}}"
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Load average",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "opensearch_os_load_average_one_minute{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "load1: {{node}}"
      },
      {
       "expr": "opensearch_os_load_average_five_minutes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "load5: {{node}}"
      },
      {
       "expr": "opensearch_os_load_average_fifteen_minutes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "load15: {{node}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "opensearch_process_cpu_percent{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "JVM memory usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "opensearch_jvm_mem_heap_used_bytes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} used: {{area}}"
      },
      {
       "expr": "opensearch_jvm_mem_heap_max_bytes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} max: {{area}}"
      },
      {
       "expr": "opensearch_jvm_mem_pool_used_bytes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} peak used pool: {{pool}}"
      }
     ]
    },
    {
     "title": "JVM memory committed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "opensearch_jvm_mem_heap_committed_bytes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} heap committed"
      },
      {
       "expr": "opensearch_jvm_mem_heap_max_bytes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} heap max"
      },
      {
       "expr": "opensearch_jvm_mem_nonheap_committed_bytes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} non-heap committed"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk and Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1-(opensearch_fs_path_available_bytes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}/opensearch_fs_path_total_bytes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"})",
       "legendFormat": "{{node}}: {{path}}"
      }
     ]
    },
    {
     "title": "Network usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(opensearch_transport_tx_bytes_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}: sent "
      },
      {
       "expr": "-irate(opensearch_transport_rx_bytes_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}: received"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Documents count on node",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "opensearch_indices_doc_number{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents indexed rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(opensearch_indices_indexing_index_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents deleted rate",
     "type": "timeseries",
     "description": "Count of deleted documents on this node",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(opensearch_indices_doc_deleted_number{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents merged rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(opensearch_indices_merges_total_number{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents merged bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(opensearch_indices_merges_total_size_bytes{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Query time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(opensearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Indexing time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(opensearch_indices_indexing_index_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Merging time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(opensearch_indices_merges_total_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Throttle time for indexing",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(opensearch_indices_indexing_throttle_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Operations status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Operations  rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(opensearch_indices_indexing_index_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: indexing"
    },
    {
     "expr": "rate(opensearch_indices_search_query_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: query"
    },
    {
     "expr": "rate(opensearch_indices_search_fetch_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: fetch"
    },
    {
     "expr": "rate(opensearch_indices_merges_total_number{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: merges"
    },
    {
     "expr": "rate(opensearch_indices_refresh_total_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: refresh"
    },
    {
     "expr": "rate(opensearch_indices_flush_total_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: flush"
    },
    {
     "expr": "rate(opensearch_indices_get_exists_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: get_exists"
    },
    {
     "expr": "rate(opensearch_indices_get_missing_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: get_missing"
    },
    {
     "expr": "rate(opensearch_indices_get_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: get"
    },
    {
     "expr": "rate(opensearch_indices_indexing_delete_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: indexing_delete"
    }
   ]
  },
  {
   "title": "Total Operations Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(opensearch_indices_indexing_index_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: indexing"
    },
    {
     "expr": "irate(opensearch_indices_search_query_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: query"
    },
    {
     "expr": "irate(opensearch_indices_search_fetch_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: fetch"
    },
    {
     "expr": "irate(opensearch_indices_merges_total_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: merges"
    },
    {
     "expr": "irate(opensearch_indices_refresh_total_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: refresh"
    },
    {
     "expr": "irate(opensearch_indices_flush_total_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: flush"
    },
    {
     "expr": "irate(elasticsearch_indices_get_exists_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: get_exists"
    },
    {
     "expr": "irate(opensearch_indices_get_exists_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: get_time"
    },
    {
     "expr": "irate(opensearch_indices_get_missing_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: get_missing"
    },
    {
     "expr": "irate(opensearch_indices_indexing_delete_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: indexing_delete"
    },
    {
     "expr": "irate(opensearch_indices_get_time_seconds{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: get"
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Thread Pool operations rejected",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(opensearch_threadpool_threads_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations queued",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "opensearch_threadpool_tasks_number{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\",type=\"queue\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Thread Pool threads active",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "opensearch_threadpool_threads_number{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\",type=\"active\"}",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Thread Pool operations completed",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(opensearch_threadpool_threads_count{instance=\"$instance\",cluster=\"$cluster\",node=~\"$node\",type=\"completed\"}[$interval])",
     "legendFormat": "{{name}}: {{ type }}"
    }
   ]
  },
  {
   "title": "Indices: Count of documents and Total size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Count of documents with only primary shards",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "opensearch_index_doc_number{instance=~\"$instance\",context=\"primaries\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total size of stored index data in bytes with only primary shards on all nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "opensearch_index_store_size_bytes{instance=~\"$instance\",context=\"primaries\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total size of stored index data in bytes with all shards on all nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "opensearch_index_store_size_bytes{instance=~\"$instance\",context=\"total\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Indices: Index writer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Index writer with only primary shards on all nodes in bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "opensearch_index_segments_memory_bytes{instance=~\"$instance\",context=\"primaries\",type=\"indexwriter\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Index writer with all shards on all nodes in bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "opensearch_index_segments_memory_bytes{instance=~\"$instance\",context=\"total\",type=\"indexwriter\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Indices: Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Segments with only primary shards on all nodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "opensearch_index_segments_number{instance=~\"$instance\",context=\"primaries\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Segments with all shards on all nodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "opensearch_index_segments_number{instance=~\"$instance\",context=\"total\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of segments with only primary shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(opensearch_index_segments_memory_bytes{instance=~\"$instance\",context=\"primaries\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Size of segments with all shards on all nodes in bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(opensearch_index_segments_memory_bytes{instance=~\"$instance\",context=\"total\"}) by (index)",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  }
 ]
}