{
 "title": "AppZ Postgres - v2",
 "description": "PostgreSQL Overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(pg_up{origin_prometheus=~\"$origin_prometheus\"},job)"
    }
   },
   {
    "name": "db",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{origin_prometheus=~\"$origin_prometheus\", job=\"$job\"},datname)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_up{origin_prometheus=~\"$origin_prometheus\", job=\"$job\"},instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(pg_up{namespace=~\"$namespace\", origin_prometheus=~\"$origin_prometheus\", job=\"$job\"},instance)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": "label_values(pg_up, namespace)" },
   {
    "name": "pod",
    "label": "Pods",
    "query": "label_values(pg_up{instance=~\"$host\", namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "PostgreSQL Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_up{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Replication Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\r\n\r\npg_settings_transaction_read_only{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"} + pg_settings_hot_standby_feedback{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}OR on() vector(3)"
    }
   ]
  },
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Connection / Transaction Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PostgeSQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=~\"$db\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=~\"$db\"}[5m])",
     "legendFormat": "commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Read Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_fetched{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=\"$db\"}[5m])",
     "legendFormat": "SELECT (index scan)"
    },
    {
     "expr": "irate(pg_stat_database_tup_returned{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "SELECT (table scan)"
    }
   ]
  },
  {
   "title": "Change Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_inserted{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=~\"$db\"}[5m])",
     "legendFormat": "INSERT"
    },
    {
     "expr": "irate(pg_stat_database_tup_updated{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "UPDATE"
    },
    {
     "expr": "irate(pg_stat_database_tup_deleted{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=~\"$db\"}",
     "legendFormat": "max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=~\"$db\"} / (pg_stat_database_blks_read{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=~\"$db\"} + pg_stat_database_blks_hit{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=~\"$db\"})",
     "legendFormat": "Cache Hit Rate"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$db\",instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=~\"$db\"}[5m])",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"$db\",instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=~\"$db\"}[5m])",
     "legendFormat": "conflicts"
    },
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=\"$db\"}[5m])",
     "legendFormat": "deadlocks"
    }
   ]
  },
  {
   "title": "Temp File",
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_temp_bytes{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=~\"$db\"}[5m])",
     "legendFormat": "Temp Bytes"
    }
   ]
  },
  {
   "title": "Lock Tables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_locks_count{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",datname=~\"$db\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}