{
 "title": "AppZ Graylog - v1",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "up{job=~\"$jobs\"}"
    }
   },
   {
    "name": "jobs",
    "query": {
     "query": "label_values(gl_buffer_process_time,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Graylog Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Graylog Cluster Input Traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(gl_traffic_input{job=\"nvdevkit2025a/graylog\"}[1d]))",
     "legendFormat": "Total Cluster Input"
    },
    {
     "expr": "increase(gl_traffic_input{job=\"nvdevkit2025a/graylog\"}[1d])",
     "legendFormat": "{{instance}} Input Traffic"
    }
   ]
  },
  {
   "title": "Graylog Cluster Output Traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(gl_traffic_output{job=\"nvdevkit2025a/graylog\"}[1d]))",
     "legendFormat": "Total Cluster Output"
    },
    {
     "expr": "increase(gl_traffic_output{job=\"nvdevkit2025a/graylog\"}[1d])",
     "legendFormat": "{{instance}} Output Traffic"
    }
   ]
  },
  {
   "title": "Graylog Journal Utilization Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(gl_journal_size{job=\"nvdevkit2025a/graylog\"} / gl_journal_size_limit{ job=\"nvdevkit2025a/graylog\"}) * 100",
     "legendFormat": "{{instance}}_journal_utilization_ratio"
    }
   ]
  },
  {
   "title": "Graylog Input Buffer Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(gl_buffer_usage{job=\"nvdevkit2025a/graylog\",type=\"input\"} / gl_buffer_size{type=\"input\", job=\"nvdevkit2025a/graylog\"}) * 100",
     "legendFormat": "{{instance}}_journal_utilization_ratio"
    }
   ]
  },
  {
   "title": "Graylog Output Buffer Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(gl_buffer_usage{job=\"nvdevkit2025a/graylog\",type=\"output\"} / gl_buffer_size{type=\"output\", job=\"nvdevkit2025a/graylog\"}) * 100",
     "legendFormat": "{{instance}}_journal_utilization_ratio"
    }
   ]
  },
  {
   "title": "Graylog Process Buffer Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(gl_buffer_usage{job=\"nvdevkit2025a/graylog\",type=\"process\"} / gl_buffer_size{type=\"process\", job=\"nvdevkit2025a/graylog\"}) * 100",
     "legendFormat": "{{instance}}_journal_utilization_ratio"
    }
   ]
  },
  {
   "title": "Graylog Daily Input By Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(gl_traffic_input{job=\"nvdevkit2025a/graylog\"}[1d]))",
     "legendFormat": "Total Graylog Cluster Input"
    },
    {
     "expr": "increase(gl_traffic_input{job=\"graylog\"}[1d])",
     "legendFormat": "{{instance}} Daily Input Traffic"
    }
   ]
  },
  {
   "title": "Graylog Daily Output By Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(gl_traffic_output{job=\"nvdevkit2025a/graylog\"}[1d]))",
     "legendFormat": "Total Graylog Cluster Output"
    },
    {
     "expr": "increase(gl_traffic_output{job=\"graylog\"}[1d])",
     "legendFormat": "{{instance}} output"
    }
   ]
  },
  {
   "title": "Graylog Buffer Utilizations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Graylog Input Buffer Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_buffer_usage{job=\"nvdevkit2025a/graylog\",type=\"input\"}",
     "legendFormat": "{{instance}}_input_buffer_usage"
    }
   ]
  },
  {
   "title": "Graylog Output Buffer Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gl_buffer_usage{type=\"output\"}",
     "legendFormat": "{{instance}}_output_buffer_usage"
    }
   ]
  },
  {
   "title": "Graylog Buffer Utilization (Combined)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(gl_buffer_usage{job=\"nvdevkit2025a/graylog\",type=\"input\"}[$__rate_interval])",
     "legendFormat": "{{instance}}_input_buffer_usage"
    },
    {
     "expr": "rate(gl_buffer_usage{job=\"graylog\",type=\"process\"}[1d])",
     "legendFormat": "{{instance}}_process_buffer_usage"
    },
    {
     "expr": "rate(gl_buffer_usage{job=\"graylog\",type=\"output\"}[1d])",
     "legendFormat": "{{instance}}_output_buffer_usage"
    }
   ]
  },
  {
   "title": "Graylog Process Buffer Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(gl_buffer_usage{job=\"nvdevkit2025a/graylog\",type=\"process\"}[1d])",
     "legendFormat": "{{instance}}_process_buffer_usage"
    }
   ]
  },
  {
   "title": "Graylog Incoming messages(Input)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gl_buffer_incoming_messages_total{job=\"nvdevkit2025a/graylog\",type=\"input\"}",
     "legendFormat": "{{instance}}_input_buffer_usage"
    }
   ]
  },
  {
   "title": "Graylog messages(Output)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gl_buffer_incoming_messages_total{type=\"output\"}",
     "legendFormat": "{{instance}}_output_buffer_usage"
    }
   ]
  },
  {
   "title": "Graylog unprocessed messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "gl_journal_entries_uncommitted", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Graylog elasticsearch output failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gl_elasticsearch_output_failures_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Graylog journal messages appended to disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "gl_journal_append_1_sec_rate", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Graylog journal read rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "gl_journal_read_1_sec_rate", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}