{
 "title": "Appz Mongo - v2",
 "tags": [
  "MongoDB",
  "Percona",
  "Prometheus "
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(mongodb_up{origin_prometheus=\"$origin_prometheus\"},job)"
    }
   },
   {
    "name": "host",
    "label": "Instance",
    "query": {
     "query": "label_values(mongodb_up{namespace=~\"$namespace\", job=\"$job\"},instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(mongodb_up, namespace)"
   },
   {
    "name": "pod",
    "label": "Pods",
    "query": "label_values(mongodb_up{instance=~\"$host\", namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health Metrics for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",state=\"available\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_connections{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",state=\"current\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Keep in mind the hard limit on the maximum number of connections set by your distribution.",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mongodb_mongod_connections{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", state=\"current\"} or\nmongodb_mongos_connections{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", state=\"current\"} or\nmongodb_connections{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", state=\"current\"} ",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "MongoDB Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_version_info{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (mongodb)",
     "legendFormat": "{{mongodb}}"
    }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU USAGE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}\r\n\r"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "mongodb_memory{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\",type=~\"resident|virtual\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_bytesIn{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval])",
     "legendFormat": "Bytes In"
    },
    {
     "expr": "rate(mongodb_ss_network_bytesOut{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval])",
     "legendFormat": "Bytes Out"
    }
   ]
  },
  { "title": "Query Metrics for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "host" },
  {
   "title": "Command Operations",
   "type": "timeseries",
   "description": "Shows how many times a command is executed per second on average during the selected interval.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", type!=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", type!=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", type!=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", type!=\"command\"}[5m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", type!~\"(command|query|getmore)\"}[$interval]) or \nirate(mongodb_mongod_op_counters_repl_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", type!~\"(command|query|getmore)\"}[5m]) or\nrate(mongodb_mongos_op_counters_repl_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", type!~\"(command|query|getmore)\"}[$interval]) or \nirate(mongodb_mongos_op_counters_repl_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", type!~\"(command|query|getmore)\"}[5m])",
     "legendFormat": "repl_{{type}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) or\nrate(mongodb_mongos_metrics_ttl_deleted_documents_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongos_metrics_ttl_deleted_documents_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "ttl_delete"
    }
   ]
  },
  {
   "title": "Query Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(mongodb_mongod_metrics_query_executor_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", state=\"scanned_objects\"}[5m]))/sum(increase(mongodb_mongod_metrics_document_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\", state=\"returned\"}[5m]))",
     "legendFormat": "Document"
    },
    {
     "expr": "sum(increase(mongodb_mongod_metrics_query_executor_total{instance=\"$host\", state=\"scanned\"}[5m]))/sum(increase(mongodb_mongod_metrics_document_total{instance=\"$host\", state=\"returned\"}[5m]))",
     "legendFormat": "Index"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "description": "When used in combination with 'Command Operations', this graph can help identify write amplification. For example, when one insert or update command actually inserts or updates hundreds, thousands, or even millions of documents.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "timeseries",
   "description": "Any number of queued operations for long periods of time is an indication of possible issues. Find the cause and fix it before requests get stuck in the queue.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or irate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or irate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "moved"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Assert Events",
   "type": "timeseries",
   "description": "Asserts are not important by themselves, but you can correlate spikes with other graphs.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_asserts_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_asserts_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) or\nrate(mongodb_mongos_asserts_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) or\nrate(mongodb_asserts_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_asserts_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "description": "Page faults indicate that requests are processed from disk either because an index is missing or there is not enough memory for the data set. Consider increasing memory or sharding out.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_extra_info_page_faults_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_extra_info_page_faults_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) or\nrate(mongodb_mongos_extra_info_page_faults_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongos_extra_info_page_faults_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) or\nrate(mongodb_extra_info_page_faults_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_extra_info_page_faults_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) ",
     "legendFormat": "Faults"
    }
   ]
  },
  {
   "title": "getLastError Write Operations",
   "type": "timeseries",
   "description": "This is useful for write-heavy workloads to understand how long it takes to verify writes and how many concurrent writes are occurring.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_get_last_error_wtime_num_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongod_metrics_get_last_error_wtime_num_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) or\nrate(mongodb_mongos_metrics_get_last_error_wtime_num_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongos_metrics_get_last_error_wtime_num_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or\nirate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) or\nrate(mongodb_mongos_metrics_get_last_error_wtimeouts_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or\nirate(mongodb_mongos_metrics_get_last_error_wtimeouts_total{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Timeouts"
    }
   ]
  },
  {
   "title": "getLastError Write Time",
   "type": "timeseries",
   "description": "This is useful for write-heavy workloads to understand how long it takes to verify writes and how many concurrent writes are occurring.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m]) or\nrate(mongodb_mongos_metrics_get_last_error_wtime_total_milliseconds{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[$interval]) or \nirate(mongodb_mongos_metrics_get_last_error_wtime_total_milliseconds{instance=\"$host\",namespace=~\"$namespace\",pod=~\"$pod\"}[5m])",
     "legendFormat": "Write Wait Time"
    }
   ]
  }
 ]
}