{
 "title": "AppZ Airflow - v2",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(airflow_job_start{origin_prometheus=~\"$origin_prometheus\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Task Instances Successes & Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(airflow_ti_successes[1m])))",
     "legendFormat": "Success"
    },
    {
     "expr": "round(sum(increase(airflow_ti_failures[1m])))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Scheduler Heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(airflow_scheduler_heartbeat[10m])*60",
     "legendFormat": "Heartbeats per Minute"
    }
   ]
  },
  {
   "title": "Scheduler Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_executable",
     "legendFormat": "Executable"
    },
    {
     "expr": "airflow_scheduler_tasks_pending",
     "legendFormat": "Pending"
    },
    {
     "expr": "airflow_scheduler_tasks_running",
     "legendFormat": "Running"
    },
    {
     "expr": "airflow_scheduler_tasks_starving",
     "legendFormat": "Starving"
    },
    {
     "expr": "airflow_scheduler_tasks_killed_externally",
     "legendFormat": "Killed Externally"
    },
    {
     "expr": "airflow_scheduler_tasks_without_dagrun",
     "legendFormat": "Without DagRun"
    }
   ]
  },
  {
   "title": "Executor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "airflow_executor_open_slots", "legendFormat": "Open Slots" },
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "Queued Tasks" },
    { "expr": "airflow_executor_running_tasks", "legendFormat": "Running Tasks" }
   ]
  },
  {
   "title": "DagBag Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "airflow_dagbag_size", "legendFormat": "DagBag Size" }
   ]
  }
 ]
}