[program:prometheus]
command                 = /appz/scripts/start.sh
user                    = root 
startretries            = 0
autostart		= true
autorestart		= true
redirect_stderr         = true
stdout_logfile	        = /appz/log/%(program_name)s.log
