[program:minio]
command                 = bash /appz/scripts/minio.sh
user                    = root
startretries            = 0
autostart		= true
autorestart		= true
stdout_logfile	        = /appz/log/%(program_name)s.log
stderr_logfile          =/appz/log/%(program_name)s.log
