[program:dockerexporter]
command                 = /usr/bin/cadvisor 
autostart               = true
autorestart             = true
stdout_logfile  = /appz/log/%(program_name)s.log
redirect_stderr = true
