/appz/log/*
{ 
        su root root 
        daily
        rotate 100
        olddir /appz/log/archive
        maxage 3
        compress
        copytruncate
        size 50M
        extension .gz
        ifempty
        
}

/appz/log/audit/*
{
        su root root
        daily
        rotate 100
        olddir /appz/log/archive
        compress
        copytruncate
        extension .gz
        ifempty
        dateext
        dateformat -%Y-%m-%d
}


